project:
  type: website

execute:
  freeze: auto

website:
  title: "数学建模与MATLAB"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
