project:
  type: website

execute:
  freeze: auto

website:
  title: "数学建模与MATLAB"
  navbar:
    left:
      - href: index.qmd
        text: 数学建模
      - href: matlab/index.qmd
        text: MATLAB
      - href: intro/index.qmd
        text: 课程介绍

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
